/**
 * List of TV Network and their country from https://www.thetvdb.com/networks
 * Since there are no easy way to get the TV Network country from thetvdb, except
 * hardcoded everything into a JSON object.
 */

const tv_network_lists = {
    "Nederlandse Publieke Omroep 1": "The Netherlands",
    "#0": "Spain",
    "+Globosat": "Brazil",
    "1+1": "Ukraine",
    "13ème rue": "France",
    "13th Street Germany": "Germany",
    "24": "Turkey",
    "2BE": "Belgium",
    "2×2": "Russia",
    "3+": "Swiss Confederation",
    "360": "Turkey",
    "3sat": "Germany",
    "4+": "Swiss Confederation",
    "5+": "Swiss Confederation",
    "5Star": "Great Britain",
    "6'eren": "Denmark",
    "6+": "Swiss Confederation",
    "6ter": "France",
    "7 RM Spain": "Spain",
    "7mate": "Australia",
    "A Haber": "Turkey",
    "A&E": "United States of America",
    "A+": "France",
    "AAG TV": "Pakistan",
    "Aaj TV": "Pakistan",
    "ABC (AU)": "Australia",
    "ABC (JA)": "Japan",
    "ABC (PH)": "Philippines",
    "ABC (US)": "United States of America",
    "ABC Family": "United States of America",
    "ABC iview": "Australia",
    "ABC News 24": "Australia",
    "ABC1": "Australia",
    "ABC2": "Australia",
    "ABC3": "Australia",
    "ABC4Kids": "Australia",
    "Abema TV": "Japan",
    "ABS-CBN Broadcasting Company": "Philippines",
    "Abu Dhabi TV": "United Arab Emirates",
    "Acorn TV": "United States of America",
    "Action": "Canada",
    "addikTV": "Canada",
    "Adult Channel": "Great Britain",
    "Adult Swim": "United States of America",
    "Aftenposten": "Norway",
    "AHC": "United States of America",
    "Aizo TV": "Taiwan",
    "Al Alam": "Iran",
    "Al Arabiyya": "United Arab Emirates",
    "Al Badeel": "Libya",
    "Al Hidaya Al Libiya": "Libya",
    "Al Jadeed": "Lebanon",
    "Al Jamahiriya TV English": "Libya",
    "Al Jazeera": "Qatar",
    "Al Jazeera America": "United States of America",
    "Al Libiya": "Libya",
    "Al Mounawaa": "Libya",
    "Al Shababiyah": "Libya",
    "Al-Jamahiriya TV": "Libya",
    "Al-Madina TV": "Libya",
    "Alibi": "Great Britain",
    "AlloCiné": "France",
    "Alnabaa": "Libya",
    "Alpha TV": "Greece",
    "Alpha TV GUJARATI": "India",
    "Alpha TV PUNJABI": "India",
    "ALT Balaji": "India",
    "Altice Studio": "France",
    "Amazon": "United States of America",
    "Amazon (Japan)": "Japan",
    "AMC": "United States of America",
    "America One Television Network": "United States of America",
    "América TV": "Argentina",
    "And TV": "India",
    "Anhui TV": "China",
    "Animal Planet": "United States of America",
    "Animax": "Japan",
    "Anime Network": "United States of America",
    "Anime OAV": "Japan",
    "ANT1": "Greece",
    "Antena 1": "Romania",
    "Antena 3": "Spain",
    "Antenne 2": "France",
    "AOL": "United States of America",
    "Apple Music": "United States of America",
    "Apple TV+": "United States of America",
    "APTN": "Canada",
    "Arena": "Australia",
    "Arirang TV": "South Korea",
    "ART TV": "Greece",
    "Arte": "France",
    "Arte Creative": "France",
    "Arte1": "Brazil",
    "ARTV": "Canada",
    "ARY Digital": "Pakistan",
    "ARY One World": "Pakistan",
    "ARY Shopping Channel": "Pakistan",
    "ARY Zouq": "Pakistan",
    "AT-X": "Japan",
    "ATN Aastha Channel": "India",
    "ATRESplayer Premium": "Spain",
    "ATV (AT)": "Austria",
    "ATV (BE)": "Belgium",
    "ATV (HK)": "Hong Kong",
    "ATV Türkiye": "Turkey",
    "Audience Network": "United States of America",
    "Australian Christian Channel": "Australia",
    "AVRO": "The Netherlands",
    "AVROTROS": "The Netherlands",
    "AXN": "United States of America",
    "AXS TV": "United States of America",
    "B4U Movies": "Great Britain",
    "B4U Music": "Great Britain",
    "B92": "Serbia",
    "BabyFirstTV": "United States of America",
    "BabyTV": "Great Britain",
    "Bandai Channel": "Japan",
    "BBC": "Great Britain",
    "BBC ALBA": "Great Britain",
    "BBC America": "United States of America",
    "BBC Canada": "Canada",
    "BBC Four": "Great Britain",
    "BBC HD": "Great Britain",
    "BBC iPlayer": "Great Britain",
    "BBC Kids": "Canada",
    "BBC News": "Great Britain",
    "BBC One": "Great Britain",
    "BBC Parliament": "Great Britain",
    "BBC Prime": "Great Britain",
    "BBC Three": "Great Britain",
    "BBC Two": "Great Britain",
    "BBC World News": "Great Britain",
    "BET": "United States of America",
    "BET+": "United States of America",
    "Beyaz TV": "Turkey",
    "Big Ten Network (BTN)": "United States of America",
    "Blackpills": "United States of America",
    "Blim": "Mexico",
    "Blip": "United States of America",
    "Bloomberg Television": "United States of America",
    "Blue Sky (Greece)": "Greece",
    "BluTV": "Turkey",
    "BNN": "Canada",
    "BNN (NL)": "The Netherlands",
    "BNN-VARA": "The Netherlands",
    "BNT1": "Bulgaria",
    "Boomerang": "Great Britain",
    "Bounce TV": "United States of America",
    "BR": "Germany",
    "BR-alpha": "Germany",
    "Bravo": "United States of America",
    "Bravo (CA)": "Canada",
    "Bravo (NZ)": "New Zealand",
    "Bravo (UK)": "Great Britain",
    "BS11": "Japan",
    "bTV": "Bulgaria",
    "Bubble Hits": "Ireland",
    "BYU Television": "United States of America",
    "C More": "Sweden",
    "C-Span": "United States of America",
    "C31": "Australia",
    "C8": "France",
    "Cable TV": "Hong Kong",
    "Canadian Learning Television": "Canada",
    "Canal 10 Saeta": "Uruguay",
    "Canal 13": "Chile",
    "Canal 4 Montecarlo": "Uruguay",
    "Canal 5": "Mexico",
    "Canal 9 (AR)": "Argentina",
    "Canal Brasil": "Brazil",
    "Canal D": "Canada",
    "Canal de las Estrellas": "Mexico",
    "Canal Famille": "Canada",
    "Canal J": "France",
    "Canal Off": "Brazil",
    "Canal Once": "Mexico",
    "Canal Q": "Portugal",
    "Canal Sony": "Brazil",
    "Canal Sur": "Spain",
    "Canal Vie": "Canada",
    "Canal+": "France",
    "Canal+ (ES)": "Spain",
    "Canal+ Cyfrowy": "Poland",
    "Canale 5": "Italy",
    "Canvas/Ketnet": "Belgium",
    "Caracol TV": "Colombia",
    "Carlton Television": "Great Britain",
    "Cartoon Hangover": "United States of America",
    "Cartoon Network": "United States of America",
    "Cartoon Network (UK)": "Great Britain",
    "Cartoon Network Australia": "Australia",
    "Cartoonito": "Great Britain",
    "Casa": "Canada",
    "CBBC": "Great Britain",
    "CBC (CA)": "Canada",
    "CBC (EG)": "Egypt",
    "CBC (JP)": "Japan",
    "CBC News Network": "Canada",
    "CBC Newsworld": "Canada",
    "CBeebies": "Great Britain",
    "CBS": "United States of America",
    "CBS All Access": "United States of America",
    "CBS Reality (UK)": "Great Britain",
    "CCTV": "China",
    "CDA": "Argentina",
    "Centric": "United States of America",
    "Česká televize": "Czech Republic",
    "Československá televize": "Czech Republic",
    "CGV": "South Korea",
    "Challenge": "Great Britain",
    "Channel 101": "United States of America",
    "Channel 2": "Israel",
    "Channel 3": "Thailand",
    "Channel 4": "Great Britain",
    "Channel 5 (SG)": "Singapore",
    "Channel 5 (TH)": "Thailand",
    "Channel 5 (UK)": "Great Britain",
    "Channel 6": "Ireland",
    "Channel 7": "Thailand",
    "Channel 8": "Singapore",
    "Channel 8 (TH)": "Thailand",
    "Channel 9": "Vietnam",
    "Channel A": "South Korea",
    "Channel U": "Singapore",
    "Channel [V]": "China",
    "Chart Show TV": "Great Britain",
    "Chérie 25": "France",
    "Chilevisión": "Chile",
    "Chiller": "United States of America",
    "CHOCO TV": "Taiwan",
    "Choice": "New Zealand",
    "Chorus Sports": "Ireland",
    "Christian Broadcasting Network": "United States of America",
    "Chubu-Nippon Broadcasting": "Japan",
    "CI": "Australia",
    "Cielo": "Italy",
    "Cine 5": "Turkey",
    "Cinemax": "United States of America",
    "CITV": "Great Britain",
    "City": "Canada",
    "City Channel": "Ireland",
    "Classic Arts Showcase": "United States of America",
    "Classic FM TV": "Great Britain",
    "Club Illico": "Canada",
    "Club RTL": "Belgium",
    "CMT": "United States of America",
    "CN8": "United States of America",
    "CNBC": "United States of America",
    "CNBC TV18": "India",
    "CNews": "France",
    "CNN": "United States of America",
    "CNNI": "United States of America",
    "Colors TV": "India",
    "Comédie !": "France",
    "Comédie+": "France",
    "Comedy (CA)": "Canada",
    "Comedy Central": "United States of America",
    "Comedy Central (FR)": "France",
    "Comedy Central (Latin America)": "United States of America",
    "Comedy Central (UK)": "Great Britain",
    "Comic-Con HQ": "United States of America",
    "Community Channel": "Great Britain",
    "Cooking Channel": "United States of America",
    "Cosmopolitan TV": "Argentina",
    "Cottage Life": "Canada",
    "Coture": "Taiwan",
    "Court TV": "United States of America",
    "CPAC": "Canada",
    "Crackle": "United States of America",
    "CraveTV": "Canada",
    "Crime & Investigation Network (AU)": "Australia",
    "Crime & Investigation Network (Europe)": "Great Britain",
    "Crime & Investigation Network (UK)": "Great Britain",
    "Crime & Investigation Network (US)": "United States of America",
    "CRTV": "United States of America",
    "CStar": "France",
    "CSTV": "South Korea",
    "CTC (JA)": "Japan",
    "CTC (RU)": "Russia",
    "CTi TV": "Taiwan",
    "CTS": "Taiwan",
    "CTV": "Canada",
    "CTV (CN)": "China",
    "CTV (JP)": "Japan",
    "CTV (TW)": "Taiwan",
    "Cuatro": "Spain",
    "CuriosityStream": "United States of America",
    "Current TV": "United States of America",
    "CW Seed": "United States of America",
    "D8": "France",
    "DaAi TV": "Taiwan",
    "Dailymotion": "United States of America",
    "Dark": "Spain",
    "Das Erste": "Germany",
    "Daum tvPot": "South Korea",
    "Dave": "Great Britain",
    "Dawn News": "Pakistan",
    "DC Universe": "United States of America",
    "DD-Gujarati": "India",
    "DDR1": "Germany",
    "DeporTV": "Argentina",
    "Destination America": "United States of America",
    "Deutsche Welle TV": "Germany",
    "Discovery": "United States of America",
    "Discovery (NL)": "The Netherlands",
    "Discovery Channel (Asia)": "Singapore",
    "Discovery Channel (AU)": "Australia",
    "Discovery Channel (CA)": "Canada",
    "Discovery Channel (PL)": "Poland",
    "Discovery Channel (SE)": "Sweden",
    "Discovery Channel (UK)": "Great Britain",
    "Discovery Family": "United States of America",
    "Discovery HD World": "Singapore",
    "Discovery History": "Great Britain",
    "Discovery Kids": "United States of America",
    "Discovery Life": "United States of America",
    "Discovery MAX": "Spain",
    "Discovery Science": "United States of America",
    "Discovery Shed": "Great Britain",
    "Discovery Turbo": "United States of America",
    "Discovery Turbo UK": "Great Britain",
    "Dish TV": "United States of America",
    "Disney Channel": "United States of America",
    "Disney Channel (BR)": "Brazil",
    "Disney Channel (DE)": "Germany",
    "Disney Channel (FR)": "France",
    "Disney Channel (IT)": "Italy",
    "Disney Channel (Latin America)": "Argentina",
    "Disney Channel (NL)": "The Netherlands",
    "Disney Channel (UK)": "Great Britain",
    "Disney Cinemagic": "Great Britain",
    "Disney Junior": "United States of America",
    "Disney Junior (UK)": "Great Britain",
    "Disney XD": "United States of America",
    "Disney XD (Latin America)": "Argentina",
    "Disney+": "United States of America",
    "DisneyLife": "Great Britain",
    "DIY Network": "United States of America",
    "DIY Network Canada": "Canada",
    "dk4": "Denmark",
    "Dlife": "Japan",
    "DMAX (DE)": "Germany",
    "DMAX (IT)": "Italy",
    "documentary Channel": "Canada",
    "Doordarshan National": "India",
    "Doordarshan News": "India",
    "Doordarshan Sports": "India",
    "Dost TV": "Turkey",
    "DR K": "Denmark",
    "DR Ramasjang": "Denmark",
    "DR1": "Denmark",
    "DR2": "Denmark",
    "DR3": "Denmark",
    "Draemong": "South Korea",
    "Dragon TV": "China",
    "DRAMAcube": "South Korea",
    "DramaH": "South Korea",
    "DramaX": "South Korea",
    "dTV": "Japan",
    "DuMont Television Network": "United States of America",
    "Duna TV": "Hungary",
    "E!": "United States of America",
    "E! (CA)": "Canada",
    "E-Channel": "South Korea",
    "e.tv": "South Africa",
    "E4": "Great Britain",
    "EBS": "South Korea",
    "Echorouk TV": "Algeria",
    "Eden": "Great Britain",
    "één": "Belgium",
    "Einsfestival": "Germany",
    "EinsPlus": "Germany",
    "El Djazairia One": "Algeria",
    "El Khabar Broadcasting Company (KBC)": "Algeria",
    "El Rey Network": "United States of America",
    "El Trece": "Argentina",
    "element14": "United States of America",
    "Eleven": "Australia",
    "Elisa Viihde": "Finland",
    "Encore": "United States of America",
    "Encuentro": "Argentina",
    "EO": "The Netherlands",
    "EPIC TV": "India",
    "EPIX": "United States of America",
    "Epsilon TV": "Greece",
    "eqhd": "Canada",
    "Eros Now": "India",
    "ERT": "Greece",
    "ESPN": "United States of America",
    "ESPN Asia": "Hong Kong",
    "ESPN Hong Kong": "Hong Kong",
    "ESPN India": "India",
    "ESPN Philippines": "Philippines",
    "ESPN Taiwan": "Taiwan",
    "Esquire Network": "United States of America",
    "ETB1": "Spain",
    "ETB2": "Spain",
    "ETTV": "Taiwan",
    "ETTV Yoyo": "Taiwan",
    "ETV": "Estonia",
    "ETV Gujarati": "India",
    "European Broadcasting Union (EBU)": "Swiss Confederation",
    "Eurosport": "Great Britain",
    "Évasion": "Canada",
    "Explora": "Canada",
    "Facebook Watch": "United States of America",
    "Family (CA)": "Canada",
    "Family CHRGD": "Canada",
    "Family Gekijo": "Japan",
    "Fantastic TV": "Hong Kong",
    "Fashion TV": "France",
    "FEARNet": "United States of America",
    "Feeln": "United States of America",
    "FEM": "Great Britain",
    "Filles TV": "France",
    "FilmOn.tv": "United States of America",
    "Five": "Great Britain",
    "Five Life": "Great Britain",
    "Five US": "Great Britain",
    "Fix & Foxi": "Germany",
    "Flooxer": "Spain",
    "FlopTV": "Italy",
    "Food Network": "United States of America",
    "Food Network Canada": "Canada",
    "Formula 1 TV (USA)": "United States of America",
    "FOX": "United States of America",
    "Fox (Latin America)": "Argentina",
    "Fox 1 (Brazil)": "Brazil",
    "Fox 1 (Latin America)": "Argentina",
    "Fox Action (Brazil)": "Brazil",
    "Fox Action (Latin America)": "Argentina",
    "Fox Action Movies": "China",
    "Fox Business": "United States of America",
    "Fox Channel (BR)": "Brazil",
    "Fox Channel (DE)": "Germany",
    "Fox Channel (FI)": "Finland",
    "Fox Channel (IT)": "Italy",
    "Fox Channel (UK)": "Great Britain",
    "Fox Cinéma": "Argentina",
    "Fox Classics": "Argentina",
    "Fox Comedy": "Argentina",
    "Fox Crime": "Italy",
    "Fox España": "Spain",
    "Fox Family": "United States of America",
    "Fox Family (Latin America)": "Argentina",
    "Fox Kids": "United States of America",
    "Fox Life (BR)": "Brazil",
    "Fox Life (IT)": "Italy",
    "Fox Life (Latin America)": "Argentina",
    "Fox Movies": "Argentina",
    "Fox News": "United States of America",
    "FOX Reality": "United States of America",
    "Fox Sports (AU)": "Australia",
    "FOX Sports 1": "United States of America",
    "Fox Sports 2": "United States of America",
    "Fox Sports Net": "United States of America",
    "FOX Traveller": "India",
    "FOX Türkiye": "Turkey",
    "FOX Türkiye (TR)": "Turkey",
    "FOX+": "Argentina",
    "Fox8": "Australia",
    "France 2": "France",
    "France 3": "France",
    "France 4": "France",
    "France 5": "France",
    "France Ô": "France",
    "france.tv": "France",
    "Fred TV": "United States of America",
    "Freeform": "United States of America",
    "fridayVideo": "Taiwan",
    "FTV": "Taiwan",
    "Fuel TV": "United States of America",
    "Fuji TV": "Japan",
    "Fullscreen": "United States of America",
    "FUNimation Channel": "United States of America",
    "Fuse": "United States of America",
    "Fusion": "United States of America",
    "Futura": "Brazil",
    "FX": "United States of America",
    "FX (BR)": "Brazil",
    "FX (Latin America)": "Argentina",
    "FXX": "United States of America",
    "FYI": "United States of America",
    "G4": "United States of America",
    "G4 Canada": "Canada",
    "Gaia": "United States of America",
    "Game One": "France",
    "GameTV Canada": "Canada",
    "Gazeta": "Brazil",
    "GEO Super": "Pakistan",
    "Geo TV": "Pakistan",
    "Global": "Canada",
    "GloboNews": "Brazil",
    "Globoplay": "Brazil",
    "Gloob": "Brazil",
    "GMA": "Philippines",
    "GMM One": "Thailand",
    "GNT": "Brazil",
    "Go90": "United States of America",
    "Golf Channel": "United States of America",
    "Great American Country": "United States of America",
    "GSN": "United States of America",
    "GTV": "Taiwan",
    "Guardian Television Network": "United States of America",
    "Gulli": "France",
    "GYAO!": "Japan",
    "H2": "United States of America",
    "Hakka TV": "Taiwan",
    "Hallmark Channel": "United States of America",
    "HBO": "United States of America",
    "HBO Asia": "Singapore",
    "HBO Canada": "Canada",
    "HBO Europe": "Hungary",
    "HBO Latin America": "Brazil",
    "HBO Magyarország": "Hungary",
    "HBO Max": "United States of America",
    "HBO Nordic": "Sweden",
    "HDNet": "United States of America",
    "here!": "United States of America",
    "HGTV": "United States of America",
    "HGTV Canada": "Canada",
    "HIFI": "Canada",
    "Hikari TV": "Japan",
    "Hír TV": "Hungary",
    "Histoire": "France",
    "Historia (CA)": "Canada",
    "Historia (ES)": "Spain",
    "History": "United States of America",
    "History (CA)": "Canada",
    "History (UK)": "Great Britain",
    "HKTV": "Hong Kong",
    "HLN": "United States of America",
    "Hoichoi": "India",
    "HOT": "Israel",
    "Hotstar": "India",
    "Hrvatska radiotelevizija": "Croatia",
    "Hulu": "United States of America",
    "hulu Japan": "Japan",
    "Hum TV": "Pakistan",
    "HUMAN": "The Netherlands",
    "Hunan TV": "China",
    "IB3": "Spain",
    "ICE TV": "Maldives",
    "ICI Tou.tv": "Canada",
    "ICTV": "Ukraine",
    "IFC": "United States of America",
    "IKON": "The Netherlands",
    "Indus Music": "Pakistan",
    "Indus News": "Pakistan",
    "Indus Vision": "Pakistan",
    "Infinity": "Italy",
    "INSP": "United States of America",
    "Investigation": "Canada",
    "Investigation Discovery": "United States of America",
    "Ion Television": "United States of America",
    "iQiyi": "China",
    "IRIB TV1": "Iran",
    "Italia 1": "Italy",
    "ITV": "Great Britain",
    "ITV Encore": "Great Britain",
    "ITV Granada": "Great Britain",
    "ITV Wales": "Great Britain",
    "ITV1": "Great Britain",
    "ITV2": "Great Britain",
    "ITV3": "Great Britain",
    "ITV4": "Great Britain",
    "ITVBe": "Great Britain",
    "ivi (Russia)": "Russia",
    "Jeuxvideo.com": "France",
    "Jiangsu TV": "China",
    "JIM": "Finland",
    "Joi": "Italy",
    "Joiz (CH)": "Swiss Confederation",
    "Joiz (DE)": "Germany",
    "Joyn (Germany)": "Germany",
    "jTBC": "South Korea",
    "June": "France",
    "Jupiter Broadcasting": "United States of America",
    "Kabel eins": "Germany",
    "Kampüs TV": "Turkey",
    "KanaalTwee": "Belgium",
    "Kanal 4 (DK)": "Denmark",
    "Kanal 5 (DK)": "Denmark",
    "Kanal 5 (SE)": "Sweden",
    "Kanal 7": "Turkey",
    "Kanal A (TR)": "Turkey",
    "Kanal D": "Turkey",
    "Kansai TV": "Japan",
    "Kashish TV": "Pakistan",
    "KBS": "South Korea",
    "KBS Joy": "South Korea",
    "KBS TV1": "South Korea",
    "KBS TV2": "South Korea",
    "KBS World": "South Korea",
    "KCET": "United States of America",
    "Kerrang! TV": "Great Britain",
    "Ketnet": "Belgium",
    "Kids and Teens TV": "United States of America",
    "Kids Station": "Japan",
    "KIKA": "Germany",
    "Kiss": "Great Britain",
    "KKTV": "Taiwan",
    "Knowledge Network": "Canada",
    "KPN Presenteert": "Belgium",
    "KRO": "The Netherlands",
    "KRO-NCRV": "The Netherlands",
    "KTN": "Kenya",
    "Kunskapskanalen": "Sweden",
    "KVOS": "United States of America",
    "Kyoto Broadcasting System": "Japan",
    "Kyushu Asahi Broadcasting": "Japan",
    "Kyushu Asahi Broadcasting (KBC)": "Japan",
    "L'Équipe 21": "France",
    "La 2 (TVE2)": "Spain",
    "La Cinq": "France",
    "La Deux": "Belgium",
    "La Red": "Chile",
    "La Siete": "Spain",
    "La Trois": "Belgium",
    "La Une": "Belgium",
    "La Uno (TVE1)": "Spain",
    "La5": "Italy",
    "La7": "Italy",
    "Lâlegül TV": "Turkey",
    "LaSexta": "Spain",
    "LCI": "France",
    "Lebanese Broadcasting Corporation International": "Lebanon",
    "LewSpears (Australia)": "Australia",
    "Liberty Channel": "United States of America",
    "Liberty TV": "Great Britain",
    "Libya Al Ahrar TV": "Libya",
    "Libya Al Riadhiya": "Libya",
    "Libya Alhurra TV": "Libya",
    "Libya Awalan TV": "Libya",
    "Life OK": "India",
    "LifeStyle": "Australia",
    "LifeStyle FOOD": "Australia",
    "LifeStyle HOME": "Australia",
    "Lifetime": "United States of America",
    "Lifetime (UK)": "Great Britain",
    "Lifetime Korea": "South Korea",
    "Line TV": "Taiwan",
    "LINE TV (TH)": "Thailand",
    "Living": "Great Britain",
    "LMN": "United States of America",
    "LNK TV": "Lithuania",
    "LOGO": "United States of America",
    "Longhorn Network": "United States of America",
    "M-Net": "South Africa",
    "M6": "France",
    "Magic": "Great Britain",
    "Magyar Televízió": "Hungary",
    "Mango TV": "China",
    "Māori Television": "New Zealand",
    "MATV": "Great Britain",
    "MavTV": "United States of America",
    "MAX": "Norway",
    "Maxdome": "Germany",
    "MBC": "South Korea",
    "MBC 1": "United Arab Emirates",
    "MBC 2 (UAE)": "United Arab Emirates",
    "MBC 3 (UAE)": "United Arab Emirates",
    "MBC 4 (UAE)": "United Arab Emirates",
    "MBC Drama": "South Korea",
    "MBC Drama (UAE)": "United Arab Emirates",
    "MBC Every1": "South Korea",
    "MBC Plus Media": "South Korea",
    "MBC Queen": "South Korea",
    "MBN": "South Korea",
    "MBS": "Japan",
    "MCE TV (Ma Chaîne Étudiante)": "France",
    "MCM": "France",
    "MCOT": "Thailand",
    "MDR": "Germany",
    "MEGA": "Chile",
    "Mega Channel": "Greece",
    "MeVue (USA)": "United States of America",
    "Military Channel": "United States of America",
    "MLB Network": "United States of America",
    "Mnet": "South Korea",
    "MNN": "United States of America",
    "Moi & Cie": "Canada",
    "Mondo TV": "Italy",
    "MoonTV": "Finland",
    "More4": "Great Britain",
    "motorsports.tv": "Great Britain",
    "MotorTrendOnDemand": "United States of America",
    "Movie Central": "Canada",
    "Movistar+": "Spain",
    "MSNBC": "United States of America",
    "MTV": "United States of America",
    "MTV (CA)": "Canada",
    "MTV (FR)": "France",
    "MTV (Lebanon)": "Lebanon",
    "MTV (PL)": "Poland",
    "MTV (UK)": "Great Britain",
    "MTV Base": "Great Britain",
    "MTV Brazil": "Brazil",
    "MTV Dance": "Great Britain",
    "MTV España": "Spain",
    "MTV Hits": "United States of America",
    "MTV Italia": "Italy",
    "MTV Latin America": "United States of America",
    "MTV Live": "United States of America",
    "MTV Mandarin": "Taiwan",
    "MTV2": "United States of America",
    "MTV3": "Finland",
    "Much (CA)": "Canada",
    "Much TV": "Taiwan",
    "Multishow": "Brazil",
    "MusiquePlus": "Canada",
    "MUTV": "Great Britain",
    "MX": "India",
    "Mya": "Italy",
    "MyNetworkTV": "United States of America",
    "myVideo": "Taiwan",
    "n-tv": "Germany",
    "Nagoya Broadcasting Network": "Japan",
    "Nat Geo Wild": "United States of America",
    "National Geographic": "United States of America",
    "National Geographic (UK)": "Great Britain",
    "NAVER tvcast": "South Korea",
    "NBA TV": "United States of America",
    "NBC": "United States of America",
    "NBC Universo": "United States of America",
    "NBCSN": "United States of America",
    "NCRV": "The Netherlands",
    "NDR": "Germany",
    "NDTV 24x7": "India",
    "NDTV India": "India",
    "NECO": "Japan",
    "Nederlandse Publieke Omroep 3": "The Netherlands",
    "Nelonen": "Finland",
    "Neox": "Spain",
    "NET 5": "The Netherlands",
    "NET.": "Indonesia",
    "Netflix": "United States of America",
    "Network Ten": "Australia",
    "New Tang Dynasty TV": "United States of America",
    "News One": "Pakistan",
    "NFL Network": "United States of America",
    "NHK": "Japan",
    "NHNZ": "New Zealand",
    "Nick App": "United States of America",
    "Nick at Nite": "United States of America",
    "Nick GAS": "United States of America",
    "Nick Jr.": "United States of America",
    "Nickelodeon": "United States of America",
    "Nickelodeon (Latin America)": "Argentina",
    "NickToons": "United States of America",
    "Niconico": "Japan",
    "Nine Network": "Australia",
    "Nitro": "Germany",
    "NoA": "France",
    "Noggin": "United States of America",
    "Nolife": "France",
    "Northern Visions Television": "Ireland",
    "NOS": "The Netherlands",
    "Nou 24": "Spain",
    "Nou Televisió": "Spain",
    "NovaTV": "Bulgaria",
    "NOVE": "Italy",
    "Now TV": "Hong Kong",
    "NRJ 12": "France",
    "NRK Super": "Norway",
    "NRK1": "Norway",
    "NRK2": "Norway",
    "NRK3": "Norway",
    "NT1": "France",
    "NTA": "Nigeria",
    "NTR": "The Netherlands",
    "NTV (JP)": "Japan",
    "NTV (TW)": "Taiwan",
    "Numéro 23": "France",
    "Oasis HD": "Canada",
    "OCN": "South Korea",
    "OCS": "France",
    "oksusu": "South Korea",
    "Olive": "South Korea",
    "OLN": "Canada",
    "Omni": "Canada",
    "Omroep Brabant": "The Netherlands",
    "Omroep MAX": "The Netherlands",
    "ONDirecTV (Latin America)": "Argentina",
    "OnStyle": "South Korea",
    "Oprah Winfrey Network": "United States of America",
    "Ora TV": "United States of America",
    "ORF 1": "Austria",
    "ORF 2": "Austria",
    "ORF III": "Austria",
    "ORTF": "France",
    "OUFtivi": "Belgium",
    "Outdoor Channel": "United States of America",
    "OutTV": "Canada",
    "Ovation TV": "United States of America",
    "Oxygen": "United States of America",
    "Pakapaka": "Argentina",
    "Paramount Channel (FR)": "France",
    "Paramount Comedy": "Great Britain",
    "Paramount Network": "United States of America",
    "Paravi": "Japan",
    "Paris Première": "France",
    "PBS": "United States of America",
    "PBS Kids Sprout": "United States of America",
    "Peacock": "United States of America",
    "Phoenix": "Germany",
    "Phoenix TV": "China",
    "Pick TV": "Great Britain",
    "Pivot": "United States of America",
    "Planet Green": "United States of America",
    "Planète+": "France",
    "Planète+ (Canada)": "Canada",
    "Play More": "Belgium",
    "Playboy TV": "United States of America",
    "Playhouse Disney": "United States of America",
    "Playhouse Disney France": "France",
    "PlayJam": "Great Britain",
    "PlayStation Network": "United States of America",
    "Playz": "Spain",
    "Plug RTL": "Belgium",
    "Polsat": "Poland",
    "Polynésie 1ère": "France",
    "Pop": "United States of America",
    "PowNed": "The Netherlands",
    "PPTV": "Thailand",
    "PREMIER (Russia)": "Russia",
    "Press TV": "Iran",
    "Prima televize": "Czech Republic",
    "PRIMA TV": "Romania",
    "Prime (BE)": "Belgium",
    "Prime (NZ)": "New Zealand",
    "Prime Box Brazil": "Brazil",
    "PRO TV": "Romania",
    "ProSieben": "Germany",
    "ProSieben Maxx": "Germany",
    "Prva Srpska Televizija": "Serbia",
    "PTS": "Taiwan",
    "PTS HD": "Taiwan",
    "PTS Taigi": "Taiwan",
    "PTV Bolan": "Pakistan",
    "PTV Global": "United States of America",
    "PTV Home": "Pakistan",
    "PTV News": "Pakistan",
    "Pub Channel": "Great Britain",
    "puhutv": "Turkey",
    "Puls 4": "Austria",
    "Pureflix": "United States of America",
    "Pursuit Channel": "United States of America",
    "PVC (UK)": "Great Britain",
    "Q TV": "Great Britain",
    "Qatar TV": "Qatar",
    "Quest": "Great Britain",
    "Quibi": "United States of America",
    "QVC": "United States of America",
    "R&R": "United States of America",
    "Radio Bremen": "Germany",
    "Radio-Canada": "Canada",
    "Radio-Québec": "Canada",
    "radX": "Canada",
    "Rai 1": "Italy",
    "Rai 2": "Italy",
    "Rai 3": "Italy",
    "Rai 4": "Italy",
    "Rai 5": "Italy",
    "Rai Gulp": "Italy",
    "RaiPlay": "Italy",
    "RBB": "Germany",
    "RCN TV": "Colombia",
    "RCTI": "Indonesia",
    "RCTV": "Venezuela",
    "RDI": "Canada",
    "Real Time": "Italy",
    "Really": "Great Britain",
    "Record": "Brazil",
    "Record News": "Brazil",
    "Red Bull TV": "United States of America",
    "Red Hot TV": "Great Britain",
    "RED+": "Colombia",
    "Rede Bandeirantes": "Brazil",
    "Rede Brasil (RBTV)": "Brazil",
    "Rede Globo": "Brazil",
    "Rede Manchete": "Brazil",
    "Rede Vida": "Brazil",
    "RedeTV!": "Brazil",
    "ReelzChannel": "United States of America",
    "Rete 4": "Italy",
    "Revelation TV": "Great Britain",
    "Revision3": "United States of America",
    "Revolt": "United States of America",
    "RLTV": "United States of America",
    "RMC Découverte": "France",
    "RMC Story": "France",
    "rmusic TV": "Great Britain",
    "Rooster Teeth": "United States of America",
    "Royal News": "Pakistan",
    "RT": "Russia",
    "RTBF": "Belgium",
    "RTBF Webcréation": "Belgium",
    "RTÉ One": "Ireland",
    "RTÉ Two": "Ireland",
    "RTÉjr": "Ireland",
    "RTF Télévision": "France",
    "RTHK": "Hong Kong",
    "RTL": "Luxembourg",
    "RTL 4": "The Netherlands",
    "RTL 5": "The Netherlands",
    "RTL 7": "The Netherlands",
    "RTL 8": "The Netherlands",
    "RTL II": "Germany",
    "RTL Klub": "Hungary",
    "RTL Television": "Germany",
    "RTL Televizija": "Croatia",
    "RTL TVI": "Belgium",
    "RTL XL": "The Netherlands",
    "RTL2": "Hungary",
    "RTLplus": "Germany",
    "RTP Açores": "Portugal",
    "RTP África": "Portugal",
    "RTP Internacional": "Portugal",
    "RTP Madeira": "Portugal",
    "RTP N": "Portugal",
    "RTP Play": "Portugal",
    "RTP1": "Portugal",
    "RTP2": "Portugal",
    "RTS Un": "Swiss Confederation",
    "RTV Noord Holland": "The Netherlands",
    "RTVC Spain": "Spain",
    "RTVS": "Slovakia",
    "RTVSLO": "Slovenia",
    "Russia Today": "Russia",
    "RÚV": "Iceland",
    "RVU": "The Netherlands",
    "S1TV": "Swiss Confederation",
    "S4/C": "Great Britain",
    "S4C2": "Great Britain",
    "Sab TV": "India",
    "SABC1": "South Africa",
    "SABC2": "South Africa",
    "SABC3": "South Africa",
    "Sahara ONE": "India",
    "Sanskar": "India",
    "SAT.1": "Germany",
    "SBS": "South Korea",
    "SBS (AU)": "Australia",
    "SBS (KR)": "South Korea",
    "SBS 6": "The Netherlands",
    "SBS Plus": "South Korea",
    "SBT": "Brazil",
    "Schweizer Fernsehen": "Swiss Confederation",
    "Science Channel": "United States of America",
    "Scuzz": "Great Britain",
    "SEC Network": "United States of America",
    "Seeso": "United States of America",
    "Semerkand TV": "Turkey",
    "Señal Colombia": "Colombia",
    "serieclub": "France",
    "Séries+": "Canada",
    "Servus TV": "Austria",
    "SET MAX": "India",
    "SET Metro": "Taiwan",
    "SET TV": "Taiwan",
    "Setanta Ireland": "Ireland",
    "Seven Network": "Australia",
    "SFR Play": "France",
    "Shahid (UAE)": "United Arab Emirates",
    "Shandong Television": "China",
    "Shenzhen TV": "China",
    "Shout! Factory (USA)": "United States of America",
    "Show TV": "Turkey",
    "Showcase (AU)": "Australia",
    "Showcase (CA)": "Canada",
    "ShowMax": "South Africa",
    "Showtime": "United States of America",
    "Shudder": "United States of America",
    "SIC": "Portugal",
    "SIC Comédia": "Portugal",
    "SIC Mulher": "Portugal",
    "SIC Notícias": "Portugal",
    "SIC Radical": "Portugal",
    "SIC Sempre Gold": "Portugal",
    "Sirasa": "Sri Lanka",
    "Sixx": "Germany",
    "Sjónvarp Símans": "Iceland",
    "Skai": "Greece",
    "Sky Arte": "Italy",
    "Sky Arts": "Great Britain",
    "Sky Atlantic (IT)": "Italy",
    "Sky Atlantic (UK)": "Great Britain",
    "Sky Box Office": "Great Britain",
    "Sky Cinema (IT)": "Italy",
    "Sky Cinema (UK)": "Great Britain",
    "Sky Crime (UK)": "Great Britain",
    "Sky Deutschland": "Germany",
    "Sky Living": "Great Britain",
    "Sky Movies": "Great Britain",
    "Sky News": "Great Britain",
    "Sky News Ireland": "Ireland",
    "SKY PerfecTV!": "Japan",
    "Sky Sports": "Great Britain",
    "Sky Travel": "Great Britain",
    "Sky Uno": "Italy",
    "Sky Witness": "Great Britain",
    "Sky1": "Great Britain",
    "Sky2": "Great Britain",
    "Sky3": "Great Britain",
    "Slash": "France",
    "Sleuth": "United States of America",
    "Slice": "Canada",
    "Smash Hits": "Great Britain",
    "Smithsonian Channel": "United States of America",
    "Smithsonian Channel (CA)": "Canada",
    "Snapchat Originals": "United States of America",
    "SOAPnet": "United States of America",
    "SoHo": "Australia",
    "Sohu TV": "China",
    "Sony Crackle": "United States of America",
    "Sony Entertainment Television": "United States of America",
    "Sony TV": "India",
    "Space": "Canada",
    "Space (Brasil)": "Brazil",
    "Space (Latin America)": "Argentina",
    "Spectrum": "United States of America",
    "Speed": "United States of America",
    "Spektrum": "Hungary",
    "Spike (NL)": "The Netherlands",
    "Spike TV": "United States of America",
    "Sportsman Channel": "United States of America",
    "SporTV": "Brazil",
    "SR": "Germany",
    "SRF 1": "Swiss Confederation",
    "Stan": "Australia",
    "Star Bharat": "India",
    "Star Channel (Greece)": "Greece",
    "STAR Chinese Channel": "Taiwan",
    "STAR Gold": "India",
    "Star Jalsha": "India",
    "Star Media": "Russia",
    "STAR Movies": "Hong Kong",
    "STAR News": "India",
    "STAR One": "India",
    "STAR Plus": "India",
    "STAR Sports Asia": "Hong Kong",
    "STAR Sports Hong Kong": "Hong Kong",
    "STAR Sports India": "India",
    "STAR Sports Malaysia": "Malaysia",
    "STAR Sports Southeast Asia": "Hong Kong",
    "STAR Sports Taiwan": "Taiwan",
    "Star TV": "Turkey",
    "STAR Vijay": "India",
    "Star World": "Hong Kong",
    "Start Russia": "Russia",
    "Starz": "United States of America",
    "Steel": "Italy",
    "Stöð 2": "Iceland",
    "Studio 100 TV": "Belgium",
    "Studio 23": "Philippines",
    "Studio 4": "France",
    "Studio+": "France",
    "STV (TW)": "Taiwan",
    "STV (UK)": "Great Britain",
    "Style": "United States of America",
    "Sub": "Finland",
    "SUN music": "India",
    "SUN news": "India",
    "Sun Television": "Japan",
    "SUN TV": "India",
    "SundanceTV": "United States of America",
    "SuoimiTV": "Finland",
    "Super Channel": "Canada",
    "Super Écran": "Canada",
    "Super!": "Italy",
    "Superstation WGN": "United States of America",
    "SVT": "Sweden",
    "SVT1": "Sweden",
    "SVT2": "Sweden",
    "SVT24": "Sweden",
    "SVTB": "Sweden",
    "Swarnawahini": "Sri Lanka",
    "Swearnet": "Canada",
    "SWR": "Germany",
    "Syfy": "United States of America",
    "Syndication": "United States of America",
    "TBN (Trinity Broadcasting Network)": "United States of America",
    "TBS": "United States of America",
    "TBS (Latin America)": "Argentina",
    "TCM": "Great Britain",
    "TEENick": "United States of America",
    "Tele 5": "Germany",
    "Télé-Québec": "Canada",
    "Telecinco": "Spain",
    "Teledoce": "Uruguay",
    "Telefe": "Argentina",
    "Telefuturo": "Paraguay",
    "TeleG": "Great Britain",
    "Telemundo": "United States of America",
    "Teletama": "Japan",
    "Télétoon": "France",
    "Teletoon": "Canada",
    "Televen": "Venezuela",
    "Televisa": "Mexico",
    "Televisión de Galicia": "Spain",
    "Television Maldives": "Maldives",
    "Television Osaka": "Japan",
    "TeleZüri": "Swiss Confederation",
    "TEN Spain": "Spain",
    "TEN Sports": "India",
    "Tencent Video": "China",
    "Terra Viva": "Brazil",
    "TestTube": "United States of America",
    "TET": "Ukraine",
    "téva": "France",
    "TevéCiudad": "Uruguay",
    "TF1": "France",
    "TF1 Séries Films": "France",
    "TFO": "Canada",
    "TFX": "France",
    "TG4": "Ireland",
    "TGRT Haber": "Turkey",
    "Thames Television": "Great Britain",
    "The 5 Network": "Philippines",
    "The Africa Channel (UK)": "Great Britain",
    "The Africa Channel (US)": "United States of America",
    "The Amp": "Great Britain",
    "The Box": "Great Britain",
    "The Comedy Channel": "Australia",
    "The CW": "United States of America",
    "The Den": "Ireland",
    "The Family Channel": "United States of America",
    "The Hub": "United States of America",
    "The Movie Network": "Canada",
    "The Sportsman Channel": "United States of America",
    "The Verge": "United States of America",
    "The WB": "United States of America",
    "The Weather Channel": "United States of America",
    "The Zeus Network": "United States of America",
    "TheBlaze": "United States of America",
    "This TV": "United States of America",
    "TIMvision": "Italy",
    "TITV": "Taiwan",
    "TLC": "United States of America",
    "TMC": "Monaco",
    "TMF": "The Netherlands",
    "TNN": "United States of America",
    "TNT (US)": "United States of America",
    "TNT Brasil": "Brazil",
    "TNT Comedy (Germany)": "Germany",
    "TNT Latin America": "Argentina",
    "TNT Serie": "Germany",
    "TNT Spain": "Spain",
    "TNU": "Uruguay",
    "Toei Channel": "Japan",
    "Toggle": "Singapore",
    "Tokyo Broadcasting System": "Japan",
    "Tokyo MX": "Japan",
    "Toon Disney": "United States of America",
    "Total Variety Network": "South Korea",
    "Tou.tv": "Canada",
    "Toute l'histoire": "France",
    "TQS": "Canada",
    "Travel + Escape": "Canada",
    "Travel Channel": "United States of America",
    "Travel Channel (UK)": "Great Britain",
    "Treehouse TV": "Canada",
    "Trend E": "South Korea",
    "TROS": "The Netherlands",
    "TRT 1": "Turkey",
    "TRT Arabic": "Turkey",
    "TRT Avaz": "Turkey",
    "TRT Belgesel": "Turkey",
    "TRT Çocuk": "Turkey",
    "TRT Diyanet": "Turkey",
    "TRT Haber": "Turkey",
    "TRT HD": "Turkey",
    "TRT Kurdî": "Turkey",
    "TRT Okul": "Turkey",
    "TRT Türk": "Turkey",
    "TRT World": "Turkey",
    "TrueID": "Thailand",
    "TrueVisions": "Thailand",
    "truTV": "United States of America",
    "TSN": "Canada",
    "TSR": "Swiss Confederation",
    "TTV": "Taiwan",
    "TTV (PL)": "Poland",
    "Turner South": "United States of America",
    "TV 2": "Norway",
    "TV 2 (DK)": "Denmark",
    "TV 2 Charlie": "Denmark",
    "TV 2 Filmkanalen": "Norway",
    "TV 2 Nyhetskanalen": "Norway",
    "TV 2 Science Fiction": "Norway",
    "TV 2 Sport": "Norway",
    "TV 2 Zebra": "Norway",
    "TV 2 Zulu": "Denmark",
    "TV 3": "Denmark",
    "TV 4": "Poland",
    "TV Aichi": "Japan",
    "TV Aparecida": "Brazil",
    "TV Asahi": "Japan",
    "TV Azteca": "Mexico",
    "TV Brasil": "Brazil",
    "TV Cabo": "Portugal",
    "TV Chile": "Chile",
    "TV Cultura": "Brazil",
    "TV Guide Channel": "United States of America",
    "TV Land": "United States of America",
    "TV Markíza": "Slovakia",
    "TV Net": "Turkey",
    "TV Nova": "Czech Republic",
    "TV One (NZ)": "New Zealand",
    "TV One (US)": "United States of America",
    "TV Osaka": "Japan",
    "TV Pública": "Argentina",
    "TV São Carlos": "Brazil",
    "TV Tokyo": "Japan",
    "TV11": "Sweden",
    "TV2 (NO)": "Norway",
    "TV2 (NZ)": "New Zealand",
    "TV24 (CH)": "Swiss Confederation",
    "TV25 (CH)": "Swiss Confederation",
    "TV3 (ES)": "Spain",
    "TV3 (IE)": "Ireland",
    "TV3 (MY)": "Malaysia",
    "TV3 (NO)": "Norway",
    "TV3 (NZ)": "New Zealand",
    "TV3 (SE)": "Sweden",
    "TV3 Puls": "Denmark",
    "TV3+": "Denmark",
    "TV4 (NZ)": "New Zealand",
    "TV4 (SE)": "Sweden",
    "TV4 Fakta": "Sweden",
    "TV4 Guld": "Sweden",
    "TV4 Komedi": "Sweden",
    "TV4 Plus": "Sweden",
    "TV4 Science Fiction": "Sweden",
    "TV5 (CA)": "Canada",
    "TV5 (FI)": "Finland",
    "TV5 (PH)": "Philippines",
    "TV5 Monde": "France",
    "TV6": "Sweden",
    "TV7 (BG)": "Bulgaria",
    "TV7 (SE)": "Sweden",
    "TV8 (IT)": "Italy",
    "TV8 (SE)": "Sweden",
    "TV8 (TR)": "Turkey",
    "TVA": "Canada",
    "TVA (JP)": "Japan",
    "TVB": "Hong Kong",
    "TVBS": "China",
    "TVBS Entertainment Channel": "Taiwan",
    "TVE": "Spain",
    "TVG Network": "United States of America",
    "TVGN": "United States of America",
    "TVI": "Portugal",
    "tvk": "Japan",
    "TVM": "Malta",
    "TVN": "Poland",
    "TVN Style": "Poland",
    "TVN Turbo": "Poland",
    "TVNorge": "Norway",
    "TVNOW (Germany)": "Germany",
    "TVNZ": "New Zealand",
    "tvN": "South Korea",
    "TVO": "Canada",
    "TVOne Global": "Pakistan",
    "TVP SA": "Poland",
    "TVP1": "Poland",
    "TVP2": "Poland",
    "TVQ (Australia)": "Australia",
    "TVQ (Japan)": "Japan",
    "TVRI": "Indonesia",
    "TVS China": "China",
    "TVS Sydney": "Australia",
    "TWiT": "United States of America",
    "Twitch": "United States of America",
    "TXN (Japan)": "Japan",
    "TYT Network": "United States of America",
    "UK Entertainment Channel": "Great Britain",
    "UKTV Drama": "Great Britain",
    "UKTV Food": "Great Britain",
    "UKTV Gold": "Great Britain",
    "UKTV History": "Great Britain",
    "UKTV Style": "Great Britain",
    "UKTV Yesterday": "Great Britain",
    "Ülke TV": "Turkey",
    "Unis TV": "Canada",
    "Universal Channel": "Brazil",
    "Universal Kids": "United States of America",
    "Univision": "United States of America",
    "UNTV 37": "Philippines",
    "UP TV": "United States of America",
    "UPN": "United States of America",
    "Urban America Television": "United States of America",
    "Urban Movie Channel": "United States of America",
    "Urdu 1": "Pakistan",
    "USA Network": "United States of America",
    "Ustream": "United States of America",
    "UTV": "Ireland",
    "V": "Canada",
    "V LIVE": "South Korea",
    "V télé": "Canada",
    "VARA": "The Netherlands",
    "Varsity TV": "United States of America",
    "Velocity": "United States of America",
    "Venevision": "Venezuela",
    "Veronica": "The Netherlands",
    "Versus": "United States of America",
    "Veteran Television": "United States of America",
    "VH1": "United States of America",
    "VH1 Brasil": "Brazil",
    "Viafree": "Sweden",
    "Viaplay": "Sweden",
    "Viasat 4": "Norway",
    "Viasat3": "Hungary",
    "Viceland (CA)": "Canada",
    "Viceland (FR)": "France",
    "Viceland (UK)": "Great Britain",
    "Viceland (US)": "United States of America",
    "VidAngel (USA)": "United States of America",
    "Videoland (NL)": "The Netherlands",
    "Videoland Television Network": "Taiwan",
    "Vidol": "Taiwan",
    "VIER": "Belgium",
    "VIJF": "Belgium",
    "VijfTV": "Belgium",
    "Vimeo": "United States of America",
    "Virgin 1": "Great Britain",
    "ViuTV": "Hong Kong",
    "Viva": "Brazil",
    "Volksmusik TV": "Germany",
    "VOX": "Germany",
    "Voyage": "France",
    "VPRO": "The Netherlands",
    "Vrak.TV": "Canada",
    "VRV": "United States of America",
    "VT4": "Belgium",
    "VTM": "Belgium",
    "vtm.be": "Belgium",
    "vtmKzoom": "Belgium",
    "Vudu": "United States of America",
    "VVVVID": "Italy",
    "W": "Australia",
    "W Network": "Canada",
    "W9": "France",
    "Warner Channel": "United States of America",
    "Warner TV": "France",
    "Watch": "Great Britain",
    "WCNY": "United States of America",
    "WDR": "Germany",
    "WE tv": "United States of America",
    "WealthTV": "United States of America",
    "Weverse (KR)": "South Korea",
    "WGN America": "United States of America",
    "WNL": "The Netherlands",
    "Workpoint TV": "Thailand",
    "WOWOW": "Japan",
    "WPIX": "United States of America",
    "WWE Network": "United States of America",
    "Xbox Video": "United States of America",
    "XtvN": "South Korea",
    "XY TV": "United States of America",
    "Yahoo! Screen": "United States of America",
    "yes": "Israel",
    "YLE": "Finland",
    "Youku": "China",
    "YouTube": "United States of America",
    "YouTube Premium": "United States of America",
    "YTV (CA)": "Canada",
    "YTV (JP)": "Japan",
    "YTV (UK)": "Great Britain",
    "ZDF": "Germany",
    "ZDF.Kultur": "Germany",
    "ZDFinfo": "Germany",
    "ZDFneo": "Germany",
    "Zee Cinema": "India",
    "Zee Gujarati": "India",
    "Zee Muzic": "India",
    "Zee TV": "India",
    "Zee5": "India",
    "Zeste": "Canada",
    "Zhejiang TV": "China",
    "ZOOM": "India",
    "Ztélé": "Canada",
    "ZTV": "Sweden",
    "Інтер": "Ukraine",
    "Дождь": "Russia",
    "Домашний": "Russia",
    "ДТВ": "Russia",
    "Звезда": "Russia",
    "НТВ": "Russia",
    "Первый канал": "Russia",
    "Пятый канал": "Russia",
    "Радио-телевизија Србије (PTC)": "Serbia",
    "РЕН": "Russia",
    "Россия 1": "Russia",
    "Россия К": "Russia",
    "СТБ": "Ukraine",
    "СТС": "Russia",
    "ТВ Центр": "Russia",
    "ТВ3": "Russia",
    "ТВС": "Russia",
    "ТНТ": "Russia",
    "הערוץ הראשון": "Israel",
    "טלעד": "Israel",
    "כאן": "Israel",
    "ערוץ 10": "Israel",
    "ערוץ הילדים‎": "Israel",
    "קשת": "Israel",
    "קשת 12": "Israel",
    "רשת": "Israel",
    "ช่อง one": "Thailand",
};

export const TVNetworks = {
    methods: {
        getTVNetwork(name) {
            if (typeof tv_network_lists[name] === 'undefined') {
                return '';
            }
            return tv_network_lists[name];
        }
    },
};